### ISSUE TITLE
Allow all tags to have a payload, so all can drop a replacement for self.

### ISSUE THREAD

**Issue by homberghp** [FontysVenlo/codestripper#10]
**You still are tied to the old java CodeStripper tags for the replacewith feature. Implementing this could drop that need.**

If you allow all tags to have a playload by default, eg
```
   //cs:remove:start:// TODO added
```
Then you can easily (with a regex ;-)) drop the old style tags from all solutions.

That is replace all 
`//_Start Solution::replacewith::_//TODO`
with `//sc:remove:start://TODO`
where the regex would be /\/\/Start Solution::replacewith::/

a sed -i strcipt can then do the trick.

**Comment by Bonajo** [comment]
There is built-in support for the [legacy tags](https://github.com/FontysVenlo/codestripper#legacy).  
The reason I don't support payload on the remove tag (for now), is because having tags on the start and the end makes it difficult to see what is being replaced. I do agree if there is only one line that gets added that it is easier to have a payload.
